"""create_social_platforms_table

Revision ID: 1de89b2c956f
Revises: 4a3a5df35a30
Create Date: 2026-07-10 09:42:07.386380
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1de89b2c956f'
down_revision = '4a3a5df35a30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_platforms_key'), 'social_platforms', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_platforms_key'), table_name='social_platforms')
    op.drop_table('social_platforms')
    # ### end Alembic commands ###
