"""add_contact_links_to_user_profile

Revision ID: 4a3a5df35a30
Revises: 20260709_0013
Create Date: 2026-07-10 09:25:15.211053
"""
"""add_contact_links_to_user_profile

Revision ID: 4a3a5df35a30
Revises: 20260709_0013
Create Date: 2026-07-10 09:25:15.211053
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4a3a5df35a30'
down_revision = '20260709_0013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('contact_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE user_profiles SET contact_links = '[]'::jsonb WHERE contact_links IS NULL")
    op.alter_column('user_profiles', 'contact_links', nullable=False)
    op.drop_constraint(op.f('user_profiles_username_key'), 'user_profiles', type_='unique')
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=False)
    op.create_unique_constraint(op.f('user_profiles_username_key'), 'user_profiles', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_profiles', 'contact_links')
    # ### end Alembic commands ###
